Add collateral verification for blocks
Constellation-Labs/tessellation pull request #313
Opened 2022-06-23 15:07 UTC by kriscieslak

2022-06-24 09:21 UTC, marcinwadon commented on modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala
> +    peersIds.toList.filterA(p => collateral.hasCollateral(id(p)))
I think you may achieve `id: A => PeerId` using `Contramap` 🤔

2022-06-24 09:21 UTC, marcinwadon approved these changes

2022-06-28 09:33 UTC, tbekas requested changes

2022-06-28 09:33 UTC, tbekas commented on modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala
> +    peersIds.toList.filterA(p => collateral.hasCollateral(WithPeerId[A].apply(p)))
`toList` is not necessary as `peersIds` is already a list.

2022-06-28 09:33 UTC, tbekas commented on modules/shared/src/main/scala/org/tessellation/schema/peer.scala
> +  type WithPeerId[A] = Function1[A, PeerId]
It doens't bring much of functionality imo. I would go with simple `_.map(_.id)` function each time when set of peers need to be verified. If you want to be fancy maybe a syntax would be enough, like:
```scala
val peers: List[Peers] = ...
peers.map(_.id).filterCollateralized(collateral)
```

2022-06-28 10:12 UTC, TheMMaciek commented on modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
>            .map(peers => peers.head)
Isn't it that right now it may throw and we should handle that?

2022-06-29 09:05 UTC, tbekas approved these changes
LGTM

2022-06-29 11:37 UTC, merged