Add default balance for not found addresses when checking collateral
Constellation-Labs/tessellation pull request #316
Opened 2022-06-27 13:05 UTC by kriscieslak

2022-06-27 13:26 UTC, marcinwadon requested changes
I think it should be labelled as `fix`, not `feature`

2022-06-27 13:38 UTC, kriscieslak commented on modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/collateral/Collateral.scala
> +        } yield balance.value >= config.amount.value
LGTM. Changed.

2022-06-27 14:48 UTC, tbekas commented on modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/collateral/CollateralSuite.scala
> +      mkCollateral(Some(Map((address1, Balance(NonNegLong(24_999_999_999_999L))))), Amount(25_000_000_000_000L))
Same here

2022-06-27 16:45 UTC, kriscieslak commented on modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/collateral/Collateral.scala
> +          .map(_.value >= config.amount.value)
Added just `order` for `Amount` as there is implicit conversion from `Balance` to `Amount`. Also had to add return type to `getBalance` method to use this conversion.

2022-06-27 16:45 UTC, kriscieslak commented on modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/collateral/CollateralSuite.scala
> +    mkCollateral(Some(Map((address1, Balance(NonNegLong(25_000_000_000_000L))))), Amount(25_000_000_000_000L))
Fixed.

2022-06-27 16:45 UTC, kriscieslak commented on modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/collateral/CollateralSuite.scala
> +      mkCollateral(Some(Map((address1, Balance(NonNegLong(24_999_999_999_999L))))), Amount(25_000_000_000_000L))
Fixed.

2022-06-28 08:32 UTC, tbekas approved these changes
LGTM

2022-06-28 08:39 UTC, merged