Added additional instructions for contributing: style guide, guidelines, and sca…
Constellation-Labs/tessellation pull request #317
Opened 2022-06-27 17:36 UTC by cngo-github

PR Type: Documentation

Added additional instructions for contributing: style guide, guidelines, and _scalafmt_.

2022-06-27 20:19 UTC, marcinwadon requested changes

2022-06-27 20:19 UTC, marcinwadon commented on CONTRIBUTING.md
> +We also use Scala's formatter, [scalafmt](https://scalameta.org/scalafmt/).
We use both `scalafmt` and `scalafix`

2022-06-27 20:19 UTC, marcinwadon commented on CONTRIBUTING.md
> +- For IntelliJ, click [here](https://www.jetbrains.com/help/idea/work-with-scala-formatter.html).
before commiting, run `sbt runLinter`

2022-06-27 21:18 UTC, cngo-github commented on CONTRIBUTING.md
> +- For IntelliJ, click [here](https://www.jetbrains.com/help/idea/work-with-scala-formatter.html).
Added.

2022-06-27 21:19 UTC, cngo-github commented on CONTRIBUTING.md
> +We roughly follow Scala's styleguide and Cat's guidelines:
Fixed.

2022-06-27 21:19 UTC, cngo-github commented on CONTRIBUTING.md
> +We roughly follow Scala's styleguide and Cat's guidelines:
Removed and replace with "Mimic the repository".

2022-06-27 22:12 UTC, cngo-github commented on CONTRIBUTING.md
> +We also use Scala's formatter, [scalafmt](https://scalameta.org/scalafmt/).
Added `scalafix` link.

2022-06-28 08:44 UTC, marcinwadon approved these changes

2022-06-28 08:44 UTC, merged