Fix calculation of last state channel snapshot hashes
Constellation-Labs/tessellation pull request #514
Opened 2022-12-08 19:52 UTC by kriscieslak

2022-12-08 22:45 UTC, marcinwadon commented on modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
> +                      }
`go.snapshot.hash.fold(_ => Eval.now(List.empty))(unfold)` ?

2022-12-13 08:53 UTC, marcinwadon approved these changes

2022-12-13 09:09 UTC, tbekas approved these changes

2022-12-13 12:17 UTC, kpudlik requested changes

2022-12-20 10:33 UTC, kpudlik approved these changes

2022-12-20 10:51 UTC, merged