Download missing incremental snapshots
Constellation-Labs/tessellation pull request #622
Opened 2023-04-19 18:02 UTC by marcinwadon

2023-04-26 21:34 UTC, cngo-github reviewed
@marcinwadon , does this affect my work regarding downloading and peer discovery (PRs https://github.com/Constellation-Labs/tessellation/pull/630 and https://github.com/Constellation-Labs/tessellation/pull/629)? Also, please update the branch.

2023-04-27 01:41 UTC, sdavidp submitted a review, later dismissed
LGTM. Left some comments.

2023-04-27 01:41 UTC, sdavidp commented on modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
> +          (peers, none[Signed[GlobalSnapshot]]).tailRecM[F, Result] {
Since it's defined above?
```suggestion
          (peers, none[Success]).tailRecM[F, Result] {
```

2023-04-27 13:01 UTC, marcinwadon commented on modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
> +          .map(_ => snapshotStorage.readTmp(nextOrdinal))
:+1:

2023-04-27 13:01 UTC, marcinwadon commented on modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
> +          (peers, none[Signed[GlobalSnapshot]]).tailRecM[F, Result] {
:+1:

2023-04-27 13:02 UTC, marcinwadon commented on modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
> +                .map { hash => // TODO: ???
yep, the code is in fact still evolving

2023-04-27 13:03 UTC, marcinwadon commented on modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
> +                }
I made self-review and spotted the same thing. Fixing :+1:

2023-04-27 13:41 UTC, marcinwadon commented
> @marcinwadon , does this affect my work regarding downloading and peer discovery (PRs #630 and #629)? Also, please update the branch.

yes

2023-05-10 14:42 UTC, kpudlik requested changes

2023-05-10 14:42 UTC, kpudlik commented on modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
> +    val fetchSnapshotDelayBetweenTrials = 10.seconds
You may consider making it a `config`

2023-05-10 14:42 UTC, kpudlik commented on modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
> +  case object UnexpectedState extends NoStackTrace
For that particular case it is probably not needed but we often introduce a sealed trait like

```scala
sealed trait DownloadError extends NoStackTrace
```

2023-05-10 14:43 UTC, kpudlik submitted a review, later dismissed

2023-05-10 22:58 UTC, marcinwadon commented on modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala
> +    val logger = Slf4jLogger.getLogger[F]
it doesn't matter as it exposes only what is defined in the trait

2023-05-11 06:21 UTC, tbekas reviewed
LGTM

2023-05-11 07:42 UTC, merged