PROT-104: Change env to Mainnet in GlobalSnapshotConsensusFunctionsSuite
Constellation-Labs/tessellation pull request #745
Opened 2023-10-12 15:28 UTC by scasplte2

## Overview
Small cleanup of a testing flag that was used during the migration to 2.0

## Approach
- Removed hardcoded testnet definition that is no longer needed in test
- Cleaned up env param that was no longer used

## Testing
- ensured unit tests pass
- awaiting CI results

## Tickets
- closed PROT-104

2023-10-13 14:00 UTC, TheMMaciek commented
Remember about adding labels to every PR - generating changelog depends on it

2023-10-16 13:27 UTC, TheMMaciek commented
@scasplte2 please set the label for this PR

2023-10-16 13:34 UTC, TheMMaciek approved these changes
LGTM, but please remember about the label. I will set it this time so that we don't merge without it.

2023-10-16 13:35 UTC, TheMMaciek requested changes
Actually please change the commit message. We are actually enabling state channel events/metagraphs on mainnet/all envs effectivelly. Changing stuff in tests is a side "quest"

2023-10-17 15:20 UTC, scasplte2 commented
Apologies for missing the label @TheMMaciek. Will be sure to follow the contributing guidelines in the future.

2023-10-17 17:06 UTC, scasplte2 commented
force pushes above were to rebase with develop since I had merged previously

2023-10-18 16:34 UTC, TheMMaciek approved these changes

2023-10-18 18:52 UTC, merged