fix: adding retry mechanism to fetch global snapshots from another peer if it fails during rollback
Constellation-Labs/tessellation pull request #924
Opened 2024-08-10 14:21 UTC by IPadawans

### Changes
+ Adding a retry mechanism of 10 times when not find the snapshot in a peer, during rollback.
+ This error was finishing the metagraph restart when we fetch from a peer that might not contain the global snapshot per hash
+ I've also added more logs to follow during the traverse.

### Tests
It's working as expected
<img width="1965" alt="Captura de Tela 2024-08-10 às 09 25 57" src="https://github.com/user-attachments/assets/5d357f1a-cf1e-4a3a-a5a6-c384af5750d0">
<img width="2501" alt="Captura de Tela 2024-08-10 às 09 39 29" src="https://github.com/user-attachments/assets/3a1f6541-9480-4145-ba9e-fb86fd535f35">

2024-08-10 18:34 UTC, marcinwadon commented on modules/shared/src/main/scala/org/tessellation/currency/dataApplication/DataApplicationTraverse.scala
> +                        .map(_.ordinal)} performing nested recursion."
`_.ordinal.show`

2024-08-10 18:35 UTC, marcinwadon commented on modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
> +          val attempts_to_fetch_global_snapshot = 10
please don't use snake case in scala

2024-08-10 18:36 UTC, marcinwadon commented on modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
> +                  logger.error("Could not get global snapshot after 10 tries") >>
message is not correlated with the variable, so it's easy to make a mistake (changing one place but not the other)

2024-08-10 18:36 UTC, marcinwadon commented on modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
> +                  logger.warn("Could not get global snapshot, trying again with another peer") >> attemptFetch(remainingAttempts - 1)
does it try with another peer indeed? I don't see any filtering of peers

2024-08-10 18:37 UTC, marcinwadon requested changes
as in comments

2024-08-10 18:38 UTC, marcinwadon commented
As I think about it - maybe the issue is not with the fetch snapshot process and your fix is just a shortcut, and the issue may be with the node status itself. There should be no possibility that node is Ready and does not answer correctly with snapshots. Or maybe we fetch from non-ready peers? Have you checked that first?

2024-08-10 18:39 UTC, marcinwadon commented on modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
> +                case None if remainingAttempts > 1 =>
is `None` returned only when peer explicitly says there is no such snapshot, or is `None` returned only when there was an error (like the node was unresponsive or there were some networking issues)?

2024-08-10 19:24 UTC, AlexBrandes commented
> As I think about it - maybe the issue is not with the fetch snapshot process and your fix is just a shortcut, and the issue may be with the node status itself. There should be no possibility that node is Ready and does not answer correctly with snapshots. Or maybe we fetch from non-ready or unresponsive peers? Have you checked that first?

In the cases that Marcus and I looked at together the nodes were in Ready state but stuck at an old ordinal, likely out of consensus but not removed from the network. The requests for snapshots were 404ing. Requests for /global-snapshots/latest (as a debug step) were succeeding but ordinal was not increasing.

I would defer to your judgement overall here but I would suggest we still include fallback behavior like this even if it should be impossible for a node to be in Ready state and not respond correctly. A retry with the issue logged would let us recover gracefully in the case of some future unknown bug even if we fix the root cause of this one.

2024-08-13 11:13 UTC, marcinwadon commented
I have opened #925 that uses cats-retry, so I'm closing this PR.

2024-08-13 11:13 UTC, closed without merging