fix: deduplicate snapshot rumors
Constellation-Labs/tessellation pull request #974
Opened 2024-11-18 01:48 UTC by effects-ai

2024-11-18 07:11 UTC, marcinwadon requested changes
I see you've closed your previous PR and opened a new one. There were some comments left, please take a look.

2024-11-18 07:11 UTC, marcinwadon commented on modules/currency-l0/src/test/scala/io/constellationnetwork/currency/l0/snapshot/SnapshotEventsPublisherDaemonSuite.scala
> +      e = {
Leftover?

2024-11-19 16:01 UTC, marcinwadon commented on modules/currency-l0/src/test/scala/io/constellationnetwork/currency/l0/snapshot/SnapshotEventsPublisherDaemonSuite.scala
> +      kp <- KeyPairGenerator.makeKeyPair[IO].toResource
`KeyPairGenerator` does not need to be a resource

2024-11-19 16:04 UTC, marcinwadon commented on modules/currency-l0/src/test/scala/io/constellationnetwork/currency/l0/snapshot/SnapshotEventsPublisherDaemonSuite.scala
> +      }
what is the Rumor type? do you have to manually play with json to extract the type of the rumor?

2024-11-19 16:06 UTC, kpudlik commented on modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/infrastructure/metrics/NoOpMetrics.scala
> +object NoOpMetrics {
I wish we had a quicker way for stubbing in tests. Unless we already have 🤔

2024-11-19 16:43 UTC, kpudlik approved these changes

2024-11-26 15:35 UTC, marcinwadon approved these changes

2024-11-26 17:05 UTC, merged